feat: added hibernation support

diff --git a/includes/copy b/includes/copy
--- a/includes/copy
+++ b/includes/copy
@@ -64,3 +64,19 @@ function copy_iwd(){
   fi
 }
 export -f copy_iwd
+
+# Copy from home/.gtkrc-2.0 to /etc/skel and $HOME
+function copy_home(){
+
+  if ! sudo cp -rfvT "$SCRIPT_DIR"/files/system/home/ "$HOME"; then
+    echo "Failed to copy .gtkrc-2.0 to /etc/skel/" >&2
+    return 1
+  fi
+
+
+  if ! sudo cp -rfvT "$SCRIPT_DIR"/files/system/home/ /etc/skel/; then
+    echo "Failed to copy .gtkrc-2.0 to /etc/skel/" >&2
+    return 1
+  fi
+}
+export -f copy_home
diff --git a/includes/stage b/includes/stage
--- a/includes/stage
+++ b/includes/stage
@@ -1,8 +1,8 @@
 #!/bin/bash
 
 #TODO
+# Add hibernation grub config and modify initramfs config to include the resume hook
 # Add nvidia drivers script
-# Add script that installs firmware based on the laptop model
 
 # shellcheck source=network
 source "$SCRIPT_DIR/includes/network"
@@ -52,6 +52,16 @@ stage_zero(){
     echo "/mnt is not mounted."
 	exit 1
   fi
+
+  # The resume hook is used for hibernation
+  add_initramfs_resume_hook
+  if ! grep -qE '^HOOKS=.*resume' /etc/mkinitcpio.conf; then
+    echo "Failed to add resume hook to mkinitcpio.conf" >&2
+    exit 1
+  fi
+
+  # Tells the kernel which swap partition is used for hibernation
+  add_resume_device_to_kernel
 
 
   # Install the linux zen-kernel with firmware
@@ -229,6 +239,11 @@ stage_two(){
 
   if ! copy_rofi_usr_theme; then
     echo "Copying rofi user theme failed" >&2
+    exit 1
+  fi
+
+  if ! copy_home; then
+    echo "Copying home directory failed" >&2
     exit 1
   fi
 
diff --git a/includes/utils b/includes/utils
--- a/includes/utils
+++ b/includes/utils
@@ -77,3 +77,51 @@ function install_model_packages(){
   fi
 }
 export -f install_model_packages
+
+function add_initramfs_resume_hook(){
+  sed -i '/^HOOKS=/s/\$)/ resume\)' /etc/mkinitcpio.conf
+}
+
+function select_swap_disk_uuid(){
+  local swap_disks
+  readarray -t swap_disks <<< "$(lsblk -lo NAME,UUID,FSTYPE | grep -i 'swap')"
+
+  if (( ${#swap_disks[@]} == 0)); then
+    echo "Error: No swap disks found" >&2
+    return 1
+  fi
+
+  local counter
+  local disk
+  counter=0
+  for disk in "${swap_disks[@]}"; do
+    echo "$counter) $disk"
+    counter=$((counter+1))
+  done
+
+  local swap_disk_index
+  swap_disk_index=0
+  if (( ${#swap_disks[@]} > 1)); then
+      read -r -p "Select swap disk: " swap_disk_index
+  fi
+
+  if [[ "$swap_disk_index" =~ ^[0-9]+$ ]] && (( "$swap_disk_index" < "${#swap_disks[@]}" )); then
+    echo "${swap_disks[$swap_disk_index]}" | cut -d' ' -f2
+  else
+    return 1
+  fi
+
+}
+export -f select_swap_disk_uuid
+
+function add_resume_device_to_kernel(){
+  local resume_device
+  while ! resume_device=$(select_swap_disk_uuid); do
+    echo "Error: Failed to select swap disk" >&2
+  done
+
+  echo "Selected swap disk UUID: $resume_device"
+  sleep 2
+  sed -i "/^GRUB_CMDLINE_LINUX_DEFAULT=/s/\"\$/ resume=UUID=$resume_device\"/" /etc/default/grub
+}
+export -f add_resume_device_to_kernel
