feat: Added printing fix: Fixed bug where hyprland wouldn't exit

diff --git a/includes/stage b/includes/stage
--- a/includes/stage
+++ b/includes/stage
@@ -240,12 +240,18 @@ stage_two(){
     exit 1
   fi
 
+  if ! add_mdns_to_nsswitch; then
+    echo "Failed to add mdns to nsswitch.conf" >&2
+    exit 1
+  fi
+
   systemctl enable --user --now pipewire
   systemctl enable --user --now pipewire-pulse
   systemctl enable --user --now wireplumber
   systemctl enable --now bluetooth
   systemctl enable tlp
   systemctl enable --now avahi-daemon
+  systemctl enable --now cups
 
   # Tells the kernel which swap partition is used for hibernation
   add_resume_device_to_kernel
diff --git a/includes/utils b/includes/utils
--- a/includes/utils
+++ b/includes/utils
@@ -142,3 +142,18 @@ function apply_gtk_theme(){
     return 1
   fi
 }
+export -f apply_gtk_theme
+
+function add_mdns_to_nsswitch(){
+
+  if grep -q 'mdns_minimal' /etc/nsswitch.conf; then
+    echo "mdns_minimal already in nsswitch!" >&2
+    return 0
+  fi
+
+  if ! sudo sed -i '/^hosts:/s/mymachines/mymachines mdns_minimal [NOTFOUND=return]/' /etc/nsswitch.conf; then
+    echo "Error: Failed to add mdns to nsswitch" >&2
+    return 1
+  fi
+}
+export -f add_mdns_to_nsswitch
