fix: Config fixes fix: Script fixes

diff --git a/includes/stage b/includes/stage
--- a/includes/stage
+++ b/includes/stage
@@ -75,11 +75,6 @@ stage_zero(){
   cp -rv "$SCRIPT_DIR"/. /mnt/opt/install/
   sudo chmod -R 777 /mnt/opt/install/
 
-  echo "Copying network configuration..."
-  if (( is_wireless )); then
-    mkdir -p /mnt/var/lib/iwd && sudo cp -r /var/lib/iwd /mnt/var/lib/
-  fi
-
   local hostname
   local username
   local password
@@ -155,7 +150,12 @@ stage_zero(){
     exit 1
   fi
 
-    if ! copy_modprobe; then
+  if ! copy_iwd; then
+    echo "Copying iwd configuration failed" >&2
+    exit 1
+  fi
+
+  if ! copy_modprobe; then
     echo "Copying modrpobe failed." >&2
     exit 1
   fi
@@ -186,14 +186,12 @@ stage_one(){
   fi
 
   echo "Installing additional model specific packages..."
-  local model_name
-  local model_packages
-  model_name=$(cat /sys/devices/virtual/dmi/id/product_name)
-  readarray -t model_packages <<< "$(export_package_group "$model_name" "pacman")"
-
-  if ! install_pacman_packages "${model_packages[@]}"; then
-    echo "Failed to install model specific packages"
-    sleep 5
+  if ! install_model_packages; then
+    echo "Failed to install model specific packages."
+    if ! ask_for_confirmation "Manual installation required. Do you want to continue?"; then
+      echo "Aborting installation."
+      exit 1
+    fi
   fi
 
   if ! install_yay_for_all; then
@@ -204,6 +202,7 @@ stage_one(){
   systemctl enable --user --now pipewire
   systemctl enable --user --now pipewire-pulse
   systemctl enable --user --now wireplumber
+  systemctl enable --now bluetooth
 
   echo "Updating stage file..."
   sudo mv /var/install/stage1 /var/install/stage2
@@ -235,11 +234,6 @@ stage_two(){
   if ! copy_dots; then
     echo "Copying modrpobe failed." >&2
     exit 1
-  fi
-
-  if ! get_best_display_config > "$HOME"/.config/hypr/monitors.conf; then
-    echo "Getting best display config failed" >&2
-    sleep 2
   fi
 
   echo "Performing cleanup..."
diff --git a/includes/utils b/includes/utils
--- a/includes/utils
+++ b/includes/utils
@@ -8,7 +8,7 @@ ask_for_confirmation(){
         return 0
         ;;
     *)
-        echo "Operation cancelled by user."
+        echo "Operation cancelled by user." >&2
         return 1
         ;;
   esac
@@ -35,7 +35,7 @@ check_root_user() {
 }
 export -f check_root_user
 
-get_current_stage_from_var() {
+function get_current_stage_from_var() {
     local stage
     stage=$(ls /var/install | grep -Eo 'stage[0-9]' | grep -Eo '[0-9]')
 
@@ -48,7 +48,7 @@ get_current_stage_from_var() {
 }
 export -f get_current_stage_from_var
 
-git_get_files_from_url(){
+function git_get_files_from_url(){
   local url=$1
   local git_dir
   git_dir=$(mktemp -d git-XXXXXXXXXX)
@@ -63,3 +63,17 @@ git_get_files_from_url(){
   fi
   echo "$git_dir"
 }
+export -f get_current_stage_from_var
+
+function install_model_packages(){
+  local model_name
+  local model_packages
+  model_name=$(cat /sys/devices/virtual/dmi/id/product_name)
+  readarray -t model_packages <<< "$(export_package_group "$model_name" "pacman")"
+
+  if ! install_pacman_packages "${model_packages[@]}"; then
+    echo "Failed to install model specific packages"
+    sleep 5
+  fi
+}
+export -f install_model_packages
